# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  hardware = {
    pulseaudio = {
      enable = true;
      support32Bit = true;
      configFile = "/home/chous/etc/pulse/pulseaudio.pa";
      package = pkgs.pulseaudioFull;
#    package = pulseaudio.override { jackaudioSupport = true; };
      daemon.logLevel = "debug";
     };
  };
 
  environment.systemPackages = with pkgs; [
    pavucontrol
    pulseaudioFull
  ];
}
