{ config, lib, pkgs, ... }:
{
    fonts = {
        enableFontDir = true;
        enableGhostscriptFonts = true;
        fonts = with pkgs; [
            #font-awesome-ttf
            freefont_ttf
            inconsolata
            powerline-fonts
            source-code-pro
            source-sans-pro
            source-serif-pro
            tewi-font
            ubuntu_font_family
            unifont
            xorg.fontscreencyrillic
            xorg.fontbitstream100dpi
            xorg.fontdaewoomisc
            xorg.fontmiscethiopic
            xorg.fontmiscmisc

            cantarell_fonts
            corefonts
            dejavu_fonts
            dina-font
            dina-font-pcf
            dosemu_fonts
            soundfont-fluid
            xorg.fontadobe100dpi
            xorg.fontadobe75dpi
            xorg.fontadobeutopia100dpi
            xorg.fontadobeutopia75dpi
            xorg.fontadobeutopiatype1
            xorg.fontalias
            xorg.fontarabicmisc
            font-awesome-ttf
            xorg.fontbh100dpi
            xorg.fontbh75dpi
            xorg.fontbhlucidatypewriter100dpi
            xorg.fontbhlucidatypewriter75dpi
            xorg.fontbhttf
            xorg.fontbhtype1
            xorg.fontbitstream100dpi
            xorg.fontbitstream75dpi
            xorg.fontbitstreamtype1
            xorg.fontcronyxcyrillic
            xorg.fontcursormisc
            xorg.fontdaewoomisc
            xorg.fontdecmisc
            font-droid
            xorg.fontibmtype1
            xorg.fontisasmisc
            xorg.fontjismisc
            xorg.fontmicromisc
            xorg.fontmisccyrillic
            xorg.fontmiscethiopic
            xorg.fontmiscmeltho
            xorg.fontmiscmisc
            xorg.fontmuttmisc
            xorg.fontschumachermisc
            xorg.fontscreencyrillic
            xorg.fontsonymisc
            xorg.fontsunmisc
            xorg.fontutil
            xorg.fontwinitzkicyrillic
            xorg.fontxfree86type1
            fontconfig_210
            fontconfig
            fontforge
            fontforge-gtk
            fontmatrix
            xorg.fontsproto
            freefont_ttf
            gnome3.gnome-font-viewer
            gohufont
            google-fonts
            gtk2fontsel
            gyre-fonts
            hack-font
            ipaexfont
            ipafont
            kawkab-mono-font
            liberation_ttf
            xorg.libfontenc
            xorg.libXfont
            xorg.libXfont2
            lohit-fonts.assamese
            lohit-fonts.bengali
            lohit-fonts.devanagari
            lohit-fonts.gujarati
            lohit-fonts.gurmukhi
            lohit-fonts.kannada
            lohit-fonts.kashmiri
            lohit-fonts.konkani
            lohit-fonts.maithili
            lohit-fonts.malayalam
            lohit-fonts.marathi
            lohit-fonts.nepali
            lohit-fonts.odia
            lohit-fonts.sindhi
            lohit-fonts.tamil
            lohit-fonts.tamil-classical
            lohit-fonts.telugu
            xorg.mkfontdir
            xorg.mkfontscale
            mplus-outline-fonts
            ocamlPackages.fontconfig
            perlPackages.FontAFM
            perlPackages.FontTTF
            powerline-fonts
            proggyfonts
#           python27Packages.fonttools
#           python35Packages.fonttools
            terminus_font
            tewi-font
# 404
#           textfonts
            ttmkfdir
            ubuntu_font_family
            unifont
            unifont_upper
            urxvt_font_size
            vistafonts
            ucsFonts
            xorg.xf86bigfontproto
            xfontsel
            xlsfonts
         ];
    };
}     
